@echo off
copy src\main.prg build\SD\MAIN 
copy src\data\sfx\sfx00.prg build\SD\SFX00
copy src\data\sfx\sfx01.prg build\SD\SFX01
copy src\data\sfx\sfx02.prg build\SD\SFX02
copy src\data\sfx\sfx03.prg build\SD\SFX03
copy src\data\sfx\sfx04.prg build\SD\SFX04
copy src\data\sfx\sfx05.prg build\SD\SFX05
copy src\data\sfx\sfx06.prg build\SD\SFX06
copy src\data\sfx\sfx07.prg build\SD\SFX07
copy src\data\sfx\sfx08.prg build\SD\SFX08
copy src\data\sfx\sfx09.prg build\SD\SFX09
copy src\data\sfx\sfx10.prg build\SD\SFX10
copy src\data\sfx\sfx11.prg build\SD\SFX11
copy src\data\sfx\sfx12.prg build\SD\SFX12
copy src\data\sfx\sfx13.prg build\SD\SFX13
copy src\data\sfx\sfx14.prg build\SD\SFX14
copy src\data\sfx\sfx15.prg build\SD\SFX15
copy src\data\sfx\sfx16.prg build\SD\SFX16
copy src\data\images\img00.prg build\SD\IMG00
copy src\data\images\img01.prg build\SD\IMG01
copy src\data\images\img02.prg build\SD\IMG02
copy src\data\images\img03.prg build\SD\IMG03
copy src\data\images\img04.prg build\SD\IMG04
copy src\data\images\img05.prg build\SD\IMG05
copy src\data\images\img06.prg build\SD\IMG06
copy src\data\images\img07.prg build\SD\IMG07
copy src\data\images\img08.prg build\SD\IMG08
copy src\data\images\img09.prg build\SD\IMG09
copy src\data\images\img10.prg build\SD\IMG10
copy src\data\images\img11.prg build\SD\IMG11
copy src\data\images\img12.prg build\SD\IMG12
copy src\data\images\img13.prg build\SD\IMG13
copy src\data\images\img14.prg build\SD\IMG14
copy src\data\images\img15.prg build\SD\IMG15
copy src\data\images\img16.prg build\SD\IMG16